version: "3"
volumes:
  psql_data: {}
services:
  postgresql:
    image: 'postgres:12.3-alpine'
    env_file:
      - .env
    volumes:
      - psql_data:/var/lib/postgresql/data
    ports:
      - 5432:5432